### ISSUE TITLE
Set database management git repository as a submodule

### ISSUE THREAD

**Issue by y1hongju** [y1hongju/aws-manager#3]
## Description

본 프로젝트의 데이터베이스를 관리하기 위한 코드들을 별도의 레포지토리에서 관리 중이었고 이를 본 레포지토리의 서브모듈로서 추가하려고 한다. 이를 위해 먼저 테스트용 임시 레포지토리를 생성하여 어떤 식으로 서브모듈이 작동하는지 확인할 예정이고, 별 문제가 없다면 데이터베이스 레포지토리를 서브모듈로 추가할 예정이다.

## TODO

- [x] 임시 레포지토리 생성 및 설정 (커밋 생성 필요)
- [x] " 서브모듈로 추가 및 이슈 체킹
- [x] 임시 레포지토리 삭제 (서브모듈, 레포지토리 자체)
- [x] 서브모듈로 데이터베이스 레포지토리 추가 및 이슈 체킹

**Comment by y1hongju** [comment]
세팅 완료.....
